egdl-1429: update plugins
ExpediaGroup/eg-oss-parent pull request #11
Opened 2020-09-23 13:15 UTC by shermosa

I **updated the plugin versions**. This PR https://github.com/ExpediaGroup/eg-oss-plugin-config/pull/5 needs to be merged first so that eg-oss-parent can use the version 1.2.0 (now 1.2.0-SNAPSHOT) of eg-oss-plugin-config.

2020-09-23 14:00 UTC, massdosage requested changes

2020-09-23 14:00 UTC, massdosage commented on CHANGELOG.md
> +
Remove this blank line please

2020-09-23 14:00 UTC, massdosage commented on pom.xml
> +    <eg.oss.plugin.config.version>1.2.0-SNAPSHOT</eg.oss.plugin.config.version>
OK, let's leave this like this until this is released as you pointed out. Then we can change this to 1.2.0 and then do the merge.

2020-09-23 14:07 UTC, abhimanyugupta07 approved these changes

2020-09-24 10:24 UTC, massdosage approved these changes

2020-09-24 10:24 UTC, merged