Added spotbugs plugin
ExpediaGroup/eg-oss-parent pull request #3
Opened 2019-08-06 07:40 UTC by cmathiesen

2019-08-06 18:29 UTC, massdosage requested changes
Also bump minor version of this project and a line in the changelog that we've added this new pluging.

2019-08-06 18:29 UTC, massdosage commented on pom.xml
> +          <excludeFilterFile>file://${project.build.directory}/plugin-config/spotbugs/hotels-spotbugs-exclude.xml</excludeFilterFile>
Update this to the filename I mentioned in the other PR.

2019-08-07 19:39 UTC, massdosage commented on pom.xml
> +    <spotbugs.config>file://${project.build.directory}/plugin-config/spotbugs/eg-spotbugs-exclude.xml</spotbugs.config>
See my comments on the similar hotels-oss PR. Let's try get it all working there and then can update this to be the same.

2019-08-10 11:49 UTC, massdosage commented on pom.xml
> +    <eg.oss.plugin.config.version>1.1.0</eg.oss.plugin.config.version>
You should add this change to the CHANGELOG too.

2019-08-12 08:59 UTC, max-jacobs commented on CHANGELOG.md
>  ## [1.0.1] - TBD
Because this 1.0.1 release is TBD and was never actually done, it can be merged with the 1.1.0 release, so you can just remove this line.

2019-08-13 14:36 UTC, patduin approved these changes

2019-08-27 12:35 UTC, massdosage approved these changes

2019-08-27 14:00 UTC, massdosage approved these changes

2019-08-27 14:01 UTC, merged